name: Backend CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1️⃣ Get source code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Login DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3️⃣ Build image
    - name: Build Docker image
      run: docker build -t karpagayalini/backend:latest .

    # 4️⃣ Push image
    - name: Push Docker image
      run: docker push karpagayalini/backend:latest

    # 5️⃣ Decode SSH private key (important fix)
    - name: Decode SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > private_key
        chmod 600 private_key

    # 6️⃣ Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key_path: private_key
        script: |
          cd ~
          ./deploy.sh
